### ISSUE TITLE
Examples too simple

### ISSUE THREAD

**Issue by davidb583** [jmeas/backbone.base-router#33]
The example folder should be enlarged with more complex application. It doesn't show advanced features / how it can be used in multiple module app.

**Comment by jmeas** [comment]
Thanks for the issue, @davidb583 !

> The example folder should be enlarged with more complex application.

Mmm...I don't think so. BaseRouter isn't fit to be used in a 'complex application' Out Of The Box. It's a way for someone to build a more complex router on top of it, which could then be used in a complex app. I would use it to build a nested router, but others might have different ideas in mind.

This library is less about overall application architecture, and more about building the router that you want, but can't make because Backbone's router is too difficult to change.

> It doesn't show advanced features

This library has a single feature: a callback [with a single argument](https://github.com/jmeas/backbone.base-router#routedata). What you do with that callback and argument is up to you!

> how it can be used in multiple module app.

How it might be used depends on what you make with it!

===

Sorry if these answers are unsatisfactory to you, but this library isn't meant to dictate how you build or structure your app. All that it does is make Backbone's Router a lot less rigid, giving you *more* freedom to do what you want.

If you're interested in thinking up ideas, then [my router comparison might be a good read.](https://github.com/jmeas/router-comparison)

**Comment by davidb583** [comment]
That's a perfect answer to my sorrows ! thanks for details.
